NODE_ENV=production
SERVICE_NAME=${SERVICE_NAME}
OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT}
PANOPTICON_API_KEY=${PANOPTICON_API_KEY}
PANOPTICON_TENANT_ID=${PANOPTICON_TENANT_ID}
PANOPTICON_INGEST_ENDPOINT=${PANOPTICON_INGEST_ENDPOINT}
DATABASE_URL=postgresql://appuser:apppassword@postgres:5432/ecommerce
# ↑ 예시입니다. 실제 운영 DB 연결 문자열에 맞게 수정하세요.
