[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name              forward
    Listen            0.0.0.0
    Port              24224
    Tag               docker.*

[FILTER]
    Name    parser
    Match   docker.*
    Key_Name log
    Parser  json
    Reserve_Data On

[OUTPUT]
    Name        http
    Match       docker.*
    Host        host.docker.internal
    Port        3005
    URI         /producer/v1/logs
    Format      json
    Json_Date_Key timestamp
    Header      Content-Type application/json
