[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info

[INPUT]
    Name              tail
    Path              /logs/*.log
    Tag               app.*
    Refresh_Interval  5
    Read_from_Head    Off
    Parser            json

[FILTER]
    Name    modify
    Match   app.*
    Add     service_name ${SERVICE_NAME}

[OUTPUT]
    Name        http
    Match       app.*
    Host        ${PANOPTICON_LOG_HOST}
    Port        ${PANOPTICON_LOG_PORT}
    URI         ${PANOPTICON_LOG_URI}
    Format      json
    Json_Date_Key timestamp
    tls         On
    Header      Content-Type application/json
